### ISSUE TITLE
Question current version

### ISSUE THREAD

**Issue by rizac** [resfahani/TFCGAN#4]
In the current version there are two additional issues to be fixed:

1. The number of generated points is 4000, meaning that, if I correctly understood the code, the length of a waveform is 40 seconds. Would it be possible to provide a custom length instead (maybe limited to some lower bound, e.g. 3 minutes or so?)?

2. According to the code:
   https://github.com/resfahani/TFCGAN/blob/02cf5f23e4d2e06af685f934898e31c6d6dfab2f/tfcgan/tfcgan.py#L272

   It lloks to me that the generated time histories is `x` (last element) and not `xh`, as we previously agreed. `xh` looks to me like an FFT (e.g. in the frequency domain). Am I correct?

   (note that we do not `squeeze()` arrays anymore for consistency when the number of waveforms is 1)

**Comment by rizac** [comment]
@resfahani when you have time can you please reply? thanks

**Comment by resfahani** [comment]
Hi, 

1- I will fix the generated points in the next model. 

2- This part has changed completely. To get the ground shaking you can run the following function:

https://github.com/resfahani/TFCGAN/blob/2c7e4369ac0e107efa6d6066c82b81d27fc40ca1/tfcgan/tfcgan.py#L151
