### ISSUE TITLE
Remove librosa or replace it with scipy

### ISSUE THREAD

**Issue by rizac** [resfahani/TFCGAN#5]
[librosa](https://librosa.org/doc/latest/core.html#module-librosa) is a python package used by tfcgan but it looks like it is used for relatively standard computations routines (fft, ifft). Also, it is conceived for different fields such as music and audio analysis which might pose installation or compatibility problems in the long run.
 
It could be more efficient to either get rid of the library, implementing our own functions, or maybe more easily replace the library with more standard and general-purpose Python libraries. For instance, scipy is a much more stable library integrated with numpy and Python. If it has all requirements for tfcgan, it could be a good idea to use scipy functions instead of librosa

Info here:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.ShortTimeFFT.html

 @resfahani please check when you have time

**Comment by resfahani** [comment]
Now, we get rid of Librosa and implement (STFT and iSTFT) from Scipy. Now, the generated waveforms are strange. It requires having a new model with data processed with the [Scipy package](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.ShortTimeFFT.html).
